### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by dethanzhang** [yangkghjh/shimo#1]
(node:35935) ExperimentalWarning: The ESM module loader is experimental.
Error: Request failed with status code 401
    at createError (/Users/zdc/zDev/GitHub/shimo/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/zdc/zDev/GitHub/shimo/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/zdc/zDev/GitHub/shimo/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by dethanzhang** [comment]
已在config.js中填入cookie。
另外，只少需要node v13才能执行~
node v12下import会报错

**Comment by yangkghjh** [comment]
更新了，现在支持 v12 了。

Cookie 是下面图中位置的一整段内容：

![Snipaste_2020-02-29_23-28-57](https://user-images.githubusercontent.com/3609399/75610354-74e41180-5b4b-11ea-8ce3-fd669d5ae739.png)
